# Generated by Django 6.0.3 on 2026-03-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=30, unique=True)),
                ('votes', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
